### ISSUE TITLE
Unable to call PSST

### ISSUE THREAD

**Issue by DanialNaeem** [kdheepak/AMES-v4.0#1]
I have installed AMES as per instructions. While running a test case, I am unable to locate and ad PATH for PSST to Environment (RUN CONFIG). How do I do so? Pls have a loom at the error message too. 

Regards

![image](https://user-images.githubusercontent.com/30325575/28433090-e980a1fe-6da3-11e7-8b51-1acedd382af9.png)

**Comment by kdheepak** [comment]
This looks like it is a PATH issue. Can you open a command line prompt and type `path` and `psst`? Please share the screenshot or copy paste the output here.

**Comment by DanialNaeem** [comment]
Actually I don't have a background in CS. Can you please be a little more specific? I am supposed to open a command prompt window and type "path and psst "?

**Comment by kdheepak** [comment]
No, sorry about that, replying from my mobile right now. `Path` is one command, `psst` is another.

**Comment by DanialNaeem** [comment]
Got it. Here 

![image](https://user-images.githubusercontent.com/30325575/28434290-41f1dfde-6da8-11e7-8bac-1f69f6e9606c.png)

**Comment by kdheepak** [comment]
Okay I'll have to get back to you on this later this evening or tomorrow. It's odd that the psst command threw an error, there is possibly some installation issues here. In addition it is possible that AMES is not able to find psst. We'll have to fix both to make it work.

**Comment by DanialNaeem** [comment]
Alright, sure.. Thanks mate

**Comment by DanialNaeem** [comment]
Any word on the solution, sir?

**Comment by kdheepak** [comment]
Sorry for the delayed response.

Can you try the following in a new folder

```bash
git clone https://github.com/kdheepak/psst.git
cd psst
pip install -e .
cd ..
psst --version
```

and send me the output you get?

**Comment by DanialNaeem** [comment]
Successfully installed e-1.4.5

Error: no such option: --version

![image](https://user-images.githubusercontent.com/30325575/28556138-cef93c7e-711d-11e7-8d4b-d02080289c70.png)

**Comment by kdheepak** [comment]
Odd. Can you try running AMES again and share the error message>

**Comment by DanialNaeem** [comment]
Still the same errors. 
Should I reinstall AMES and psst?

![image](https://user-images.githubusercontent.com/30325575/28556445-db7053aa-711f-11e7-95f1-6ab1f8ee6b5f.png)

**Comment by kdheepak** [comment]
Are you using Eclipse? Did you make sure you checked [this](https://github.com/kdheepak/AMES-v4.0/blob/master/images/image4.png)?

**Comment by DanialNaeem** [comment]
I am using Eclipse. 
This is what I have

![image](https://user-images.githubusercontent.com/30325575/28560442-18bd57a8-7134-11e7-9b79-5229b3be0671.png)

**Comment by kdheepak** [comment]
Thanks for sharing that. Can you share the full string that is in value of the `Path` variable? Or can you check if Anaconda is in there? If not, that might be your issue.

**Comment by DanialNaeem** [comment]
C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd

Yes, apparently there is no anaconda.

**Comment by kdheepak** [comment]
Can you open a command line again, and type `pip --version`?

**Comment by DanialNaeem** [comment]
Yes, it retuns

pip 9.0.1 from C:\Users\dannn\Anaconda3\lib\site-packages (python 3.6)

**Comment by kdheepak** [comment]
I'm surprised that `psst --version` does not return the version number. This is the output from my computer right now.

```bash
$ psst --version
psst, version 0.1.0
```

Anyway, you should be able to add the following to your `Path` in Eclipse.

```bash
C:\Users\dannn\Anaconda3\lib\site-packages;C:\Users\dannn\Anaconda3\bin;C:\Users\dannn\Anaconda3\Scripts;
```

**Comment by DanialNaeem** [comment]
Added the path Sir. Got rid of the old error message, but here's a new one.

![image](https://user-images.githubusercontent.com/30325575/28561314-5aa1f9fa-7137-11e7-965f-1cbc0039df3f.png)

And what do I do of psst? Reinstall?

**Comment by kdheepak** [comment]
Hmmm. It'll be easier if we can do some sort of screen sharing, so that I can see more clearly what is going on. 

If you scroll up in this output log, you should see another error message from `psst`. If you can share that that will be great.

**Comment by DanialNaeem** [comment]
Is it possible for you to have a little skype session?

AMES gets to return ModuleNotFoundError: No module named 'psst.model'
![image](https://user-images.githubusercontent.com/30325575/28561678-c74fe3d6-7138-11e7-94a8-333177125ccf.png)

**Comment by kdheepak** [comment]
Okay, Send me a private message / email.

**Comment by DanialNaeem** [comment]
Emailed

**Comment by kdheepak** [comment]
Path issues 

- Two versions of pip were installed. Made pip from conda higher priority
- Path to CBC solver needs to be added to Eclipse as well

These resolved the issues.
