### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by rohithreddy95** [kdheepak/AMES-v4.0#2]
Error while running the case - 8BusTestCase_8gen.dat (as shown in the INSTALL.md file) with the exception caused by java.io.FileNotFoundException: xfertoames.dat

**Comment by kdheepak** [comment]
Can you list the OS, the version of Python you are using and attach screenshots? It's likely that AMES is not able to find psst when trying to solve the SCUC.

**Comment by rohithreddy95** [comment]
I'm running it on Windows 10, with python 3.6.1
![errorlog](https://user-images.githubusercontent.com/5306174/31512608-2e9a3e32-af51-11e7-87ef-8c4398e9126d.png)

**Comment by kdheepak** [comment]
Yeah, so that error is because it is not able to find the CBC solver. Have you installed that? 

You can also set it up to use CPLEX or any other solver supported by [Pyomo](github.com/pyomo/pyomo). You will need to update your environment variable `PSST_SOLVER` to the name of the solver you want. CBC is the default.

**Comment by rohithreddy95** [comment]
I've previously installed CPLEX as the optimizer but didn't set the corresponding environment variable. This might be a trivial question, but I couldn't find the environment variable PSST_SOLVER anywhere, where do I update the variable? As you've said that CBC is the default solver, the temporary workaround was to install CBC. The example is now running without any errors with CBC.

**Comment by kdheepak** [comment]
[This](https://www.java.com/en/download/help/path.xml) describes it for Windows. 

![windows_environment_variables](https://user-images.githubusercontent.com/1813121/31521433-c3b14776-af66-11e7-90eb-649bd3236048.png)
![image4](https://user-images.githubusercontent.com/1813121/31521440-c7d68046-af66-11e7-96c9-05bfa042a066.png)

**Comment by rohithreddy95** [comment]
So, in this in environment variables, I did not find any variable named PSST_SOLVER. Do I need to create a new variable called PSST_SOLVER?

**Comment by kdheepak** [comment]
Yes you'd have to create a new one. Sorry for the terse replies, I'm on my mobile.

**Comment by 1152833988** [comment]
> Sorry for the terse replies
So, what should I do to creat the path PSST_SOLVER

**Comment by 1152833988** [comment]
> Error while running the case - 8BusTestCase_8gen.dat (as shown in the INSTALL.md file) with the exception caused by java.io.FileNotFoundException: xfertoames.dat

Have you solved this problem? Now I have also encountered this problem。

**Comment by kdheepak** [comment]
Can you check your environment variables? You create an environment variable called `PSST_SOLVER` similar to the screenshot above.

**Comment by 1152833988** [comment]
> Can you check your environment variables? You should have or create an environment variable called `PSST_SOLVER` similar to the screenshot above.

I creat the PSST_SOLVER by myself, and now it shows this mistake 
![捕获](https://user-images.githubusercontent.com/54027278/63430827-23e2ba80-c450-11e9-99d2-c0a072a14419.PNG)
![捕获2](https://user-images.githubusercontent.com/54027278/63430831-26ddab00-c450-11e9-92e6-d99efb43aa36.PNG)

**Comment by kdheepak** [comment]
Type conda install numpy scipy pandas

**Comment by kdheepak** [comment]
Type `conda install numpy`. You may also need to install `scipy`, `pandas` and other python dependencies if it doesn't work.

```
conda install numpy
conda install scipy
conda install pandas
conda install matplotlib
```

If you are missing any other packages, such as pure Python packages you can use `pip` to install them.

```
pip install pyomo
```

**Comment by gaoyuan22** [comment]
I  also encountered this problem.According to your suggestion, I  have installed cbc and modified the path in the program. Now it shows this mistake：

![QQ截图20190823100936](https://user-images.githubusercontent.com/54423684/63561962-65797f80-c58e-11e9-90cd-8932fdbf5be2.png)
![QQ截图20190823101024](https://user-images.githubusercontent.com/54423684/63561970-6f02e780-c58e-11e9-8fcd-ec35df109b17.png)

**Comment by kdheepak** [comment]
Are you sure you installed the right version of psst?

https://github.com/kdheepak/AMES-v4.0/blob/master/psst/psst/model/__init__.py#L35

**Comment by kdheepak** [comment]
Open your Anaconda prompt and run

```
pip uninstall psst
```

Then follow the instructions here:

https://github.com/kdheepak/AMES-v4.0/blob/master/INSTALL.md#install-psst

**Comment by kdheepak** [comment]
Also, using Python3 is recommended.

**Comment by gaoyuan22** [comment]
Thank you,I have checked the psst and it shows this mistake:

**Comment by gaoyuan22** [comment]
![微信图片_20190824110649](https://user-images.githubusercontent.com/54423684/63631865-6cbc8e00-c65f-11e9-89aa-445d967b9900.jpg)

**Comment by kdheepak** [comment]
Hmm. The version of pandas being used must be new. I'll see if I can push a fix later tonight.

**Comment by kdheepak** [comment]
@gaoyuan22 where did you install `psst` from? It looks like you've cloned `psst` from somewhere? In your stacktrace it shows: `c:\users\david\gitrepos\psst\psst\model\__init__.py`. 

AMES-v4.0 is only compatible with this version of `psst`: https://github.com/kdheepak/AMES-v4.0/tree/master/psst/psst

**Comment by gaoyuan22** [comment]
I am sorry to ask you again, I have encountered a new problem：
![QQ截图20190826143859](https://user-images.githubusercontent.com/54423684/63670571-af24cd00-c80f-11e9-91ec-16444c00dde9.png)
![QQ截图20190826143941](https://user-images.githubusercontent.com/54423684/63670574-b1872700-c80f-11e9-8c4a-63409aeb0a32.png)

**Comment by gaoyuan22** [comment]
The result has changed
![QQ截图20190826203324](https://user-images.githubusercontent.com/54423684/63691057-d1830e80-c840-11e9-8a1f-324c7c2d1e6f.png)
:

**Comment by kdheepak** [comment]
I think this means it's working!

**Comment by gaoyuan22** [comment]
Thank you again,but I also have a question: why the result includes “failed to create process " for every day

**Comment by kdheepak** [comment]
Hmm. I've never seen that before. Can you search the local directory for .log files or .dat files and look inside them to see if you find anything relevant?

**Comment by gaoyuan22** [comment]
OK! Thank you
